### ISSUE TITLE
request for future update

### ISSUE THREAD

**Issue by rotem154154** [Jeck-Sparrow-5/MapleWeb#2]
Hi great work (:
I am playing for 100 hours in your server and I encouter some problems:

1. Not want bow
2. Free market is not free
3. bad music
4. to much people in the sever
5. to much classes, balance the game
6. I am alredy level 220 and still do mises on snail. its your fault
7. No support to 3d yet, learn unity dude
8. request for chrome extenstion to play for me, I am lazy
9. you dont have any classes, add some dude
10. I hate the name call it yeou or something I dont need to do the job for you
11. the version is too high I want without the pirate
12. cool job
13. no support for vision pro... yet
14. no support for android... great job

Bad job

**Comment by Jeck-Sparrow-5** [comment]
Hi thanks for playing for 100 hours, with the current state of the game it's impressive 
1. you can change to any weapon (change the bow to a glove and the shooting projectile to a thorwing star and you'r an assassin 
2. There is a free market? I didn't know. Thanks for telling me 
3. What? did you change the music or something? I recommend Kerning city for the best music 
4. Where?
5. There is zero classes at the moment. Do you want less than zero?
6. wow that's impressive 
7. We can do maybe 3d glasses with red and blue
8. That's a cool idea
9. So you want less than zero and more than zero classes (That's hard to solve but I'll try)
10. Yeou is already taken.. Do you have other suggestions?
11. There isn't a pirate... (yet)
12. Thanks
13. Did you try? becasue it's working you jsut need to use the virtual keyboard there or a bluetooth one
14. Didn't know this but cool
